# This config is based on Spring Docker Compose support
# https://spring.io/blog/2023/06/21/docker-compose-support-in-spring-boot-3-1
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: movieman
      POSTGRES_USER: movieman
      POSTGRES_PASSWORD: mayonnaise1
  adminer:
    image: adminer
    restart: always
    ports:
      - 5442:8080
