version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: movieman
      POSTGRES_PASSWORD: mayonnaise1
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
