# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "feature/**", "story/**", "bugfix/**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper

    - name: Build and Unit Test with Gradle
      run: gradle test

    - name: Run Integration Tests
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
      run: gradle integrationTest

    - name: Jacoco Coverage Report
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.JACOCO_TOKEN }}
        update-comment: true
        title: 'JaCoCo Report'
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        pass-emoji: ':white_check_mark:'
        fail-emoji: ':x:'
